/** Arabic dictionary for documentHtml (zh/en). Generated by translate2.py. */
export const ar = {
  title: 'HTML',
  frame: 'معاينة مستند HTML',
  loading: 'جارٍ القراءة…',
  failed: 'تعذّرت معاينة هذا المستند HTML',
} as const
