/** Arabic dictionary for documentMarkdown (zh/en). Generated by translate2.py. */
export const ar = {
  'viewer.label': 'Markdown',
  'code.copy': 'نسخ',
  'code.copied': 'تم النسخ',
  'footnotes': 'الحواشي',
} as const
