/** Arabic dictionary for goal (zh/en). Generated by translate2.py. */
export const ar = {
  'phase.active': 'الهدف الجاري',
  'phase.active.disarmed': 'الهدف غير النشط',
  'phase.paused': 'الهدف الموقّت',
  'phase.blocked': 'الهدف المعطّل',
  'objective.aria': 'محتوى الهدف',
  'commandInput.aria': 'إدخال الأمر',
  'action.save': 'حفظ الهدف',
  'action.cancel': 'إلغاء التعديل',
  'action.pause': 'إيقاف الهدف مؤقتًا',
  'action.resume': 'استئناف الهدف',
  'action.edit': 'تعديل الهدف',
  'action.clear': 'مسح الهدف',
} as const
