/** Arabic dictionary for job (zh/en). Generated by translate2.py. */
export const ar = {
  'count.live.one': '{count} مهمة خلفية قيد التشغيل',
  'count.live.other': '{count} مهام خلفية قيد التشغيل',
  'count.idle.one': '{count} مهمة خلفية',
  'count.idle.other': '{count} مهام خلفية',
  'list.aria': 'المهام الخلفية',
  'status.running': 'قيد التشغيل',
  'status.stopping': 'جارٍ الإيقاف',
  'status.completed': 'مكتملة',
  'status.killed': 'ملغاة',
  'status.failed': 'فاشلة',
  'duration.seconds': '{seconds} ثانية',
  'duration.minutes': '{minutes} دقيقة {seconds} ثانية',
  'duration.hours': '{hours} ساعة {minutes} دقيقة',
  'duration.title.live': 'قيد التشغيل منذ {duration}',
  'duration.title.done': 'استغرق {duration}',
} as const
