/** Arabic dictionary for plan (zh/en). Generated by translate2.py. */
export const ar = {
  'chip.label': 'الخطة',
  'chip.on.aria': 'وضع التخطيط مفعّل، اضغط للإيقاف',
  'chip.on.title': 'وضع التخطيط مفعّل — انقر للإيقاف (/plan off)',
  'chip.off.aria': 'وضع التخطيط معطّل، اضغط للتفعيل',
  'chip.off.title': 'وضع التخطيط معطّل — انقر للتفعيل (/plan)',
  'chip.exitFailed': 'فشل في الخروج من وضع التخطيط',
} as const
