/** Arabic dictionary for question (zh/en). Generated by translate2.py. */
export const ar = {
  'error.incomplete': 'يرجى إكمال هذا السؤال أولاً.',
  'error.unanswered': 'يرجى اختيار خيار أو إدخال إجابة مخصصة.',
  'nav.prev': 'السؤال السابق',
  'nav.next': 'السؤال التالي',
  'nav.minimize': 'طيّ بطاقة السؤال',
  'nav.maximize': 'توسيع بطاقة السؤال',
  'nav.cancel': 'إلغاء جميع الأسئلة',
  'option.recommended': 'موصى به',
  'custom.placeholder': 'اكتب إجابتك',
  'action.skip': 'تخطٍّ',
  'action.next': 'التالي',
  'plan.header': 'مراجعة الخطة',
  'plan.approve': 'اعتماد التنفيذ',
  'plan.decline': 'رفض',
  'plan.discuss': 'ناقش في المحادثة',
} as const
