/** Arabic dictionary for reference (zh/en). Generated by translate2.py. */
export const ar = {
  'section.files': 'الملفات والمجلدات',
  'section.sessions': 'الجلسات',
  'candidate.noCwd': '(بدون مجلد عمل)',
  'crumb.root': 'مساحة العمل',
  'time.now': 'الآن',
  'time.minutes': '{n} دقيقة',
  'time.hours': '{n} ساعة',
  'time.days': '{n} يوم',
  'time.months': '{n} شهر',
  'time.years': '{n} سنة',
} as const
