/** Arabic dictionary for session-log-download (zh/en). Generated by translate2.py. */
export const ar = {
  'header.more': 'المزيد من الإجراءات',
  'menu.download': 'تنزيل سجل Session',
  'dialog.preparingTitle': 'جارٍ تصدير Session',
  'dialog.preparingDescription': 'جارٍ تجهيز ملف ZIP يحتوي على Session الحالي والجلسات الفرعية والمرفقات.',
  'dialog.successTitle': 'بدأ تنزيل Session',
  'dialog.successDescription': 'يتم تنزيل ملف ZIP الخاص بـ Session بواسطة المتصفح.',
  'dialog.errorTitle': 'فشل تصدير Session',
  'dialog.close': 'إغلاق',
  'dialog.commandFailed': 'تعذّر بدء تصدير Session.',
} as const
