/** Arabic dictionary for settings.archivedSessions (zh/en). Generated by translate2.py. */
export const ar = {
  nav: 'الجلسات المؤرشفة',
  search: 'البحث في الجلسات المؤرشفة',
  loading: 'جارٍ قراءة الجلسات…',
  empty: 'لا توجد جلسات مؤرشفة.',
  unavailable: 'لا توجد جلسة مؤرشفة هنا يمكن استعادتها.',
  emptySearch: 'لا توجد جلسات مطابقة.',
  unarchive: 'إلغاء الأرشفة',
  unarchiveNamed: 'إلغاء أرشفة {title}',
  ungrouped: 'غير مجمّعة',
  'time.now': 'الآن',
  'time.minutes': '{n} دقيقة',
  'time.hours': '{n} ساعة',
  'time.days': '{n} يوم',
  'time.months': '{n} شهر',
  'time.years': '{n} سنة',
} as const
