/** Arabic dictionary for settings (zh/en). Generated by translate2.py. */
export const ar = {
  'trigger': 'الإعدادات',
  'title': 'الإعدادات',
  'close': 'إغلاق',
  'openDocument': 'فتح ملف الإعدادات',
  'openDocument.error': 'تعذّر فتح ملف الإعدادات',
  'general.nav': 'عام',
  'connection.error': 'خطأ في الاتصال، أعد التحميل للمحاولة',
  'connection.connecting': 'جارٍ إعادة الاتصال',
  'connection.connected': 'تم الاتصال بنجاح',
  'connection.reconnect': 'خطأ في الاتصال، انقر لإعادة الاتصال الآن',
  'connection.restart': 'انقطاع الاتصال، جارٍ إعادة المحاولة، انقر لإعادة الاتصال الآن',
} as const
