/** Arabic dictionary for settings.permission (zh/en). Generated by translate2.py. */
export const ar = {
  'title': 'الصلاحيات',
  'description': 'اختر وضع الصلاحيات الافتراضي للجلسات الجديدة',
  'loading': 'جارٍ التحميل',
  'unavailable': 'غير متوفر',
  'preset.readOnly': 'قراءة فقط',
  'preset.workspaceWrite': 'تعديل في مساحة العمل',
  'preset.fullAccess': 'صلاحيات كاملة',
  'confirm.title': 'تأكيد تفعيل الصلاحيات الكاملة؟',
  'confirm.description': 'بعد تفعيل الصلاحيات الكاملة، ستقلل الجلسات الجديدة من خطوات التأكيد وستتمكن من تنفيذ المزيد من الإجراءات مباشرةً، بما في ذلك العمليات الحساسة، وتعديل الملفات، أو الأوامر الخارجية. يُنصح باستخدامها فقط عند ثقتك بالمهام اللاحقة.',
  'confirm.acknowledge': 'أدرك المخاطر وأرغب في المتابعة',
  'confirm.cancel': 'إلغاء',
  'confirm.enable': 'تفعيل الصلاحيات الكاملة',
} as const
