/** Arabic dictionary for sidebarImage (zh/en). Generated by translate2.py. */
export const ar = {
  title: 'صورة',
  preview: 'معاينة الصورة: {name}',
  loading: 'جارٍ القراءة…',
  failed: 'تعذّر عرض هذه الصورة',
  unsupported: 'تتطلب معاينة الصورة محتوى الملف الكامل',
} as const
