/** Arabic dictionary for sidebarPdf (zh/en). Generated by translate2.py. */
export const ar = {
  title: 'PDF',
  pageImage: 'صفحة {page} من PDF',
  loading: 'جارٍ القراءة…',
  rendering: 'جارٍ رسم الصفحة…',
  failed: 'تعذّر عرض PDF: {message}',
  password: 'يتطلب هذا الملف كلمة مرور، ولا يُدعم عرض الملفات المحمية بكلمة مرور',
  workerFailed: 'تعذّر مواصلة عملية عرض PDF، يرجى المحاولة مرة أخرى',
  unsupported: 'يتطلب عرض PDF محتوى الملف الكامل',
  retry: 'إعادة المحاولة',
} as const
