/** Arabic dictionary for sidebarFiles (zh/en). Generated by translate2.py. */
export const ar = {
  'type.label': 'الملفات',
  'guide.title': 'ملفات مساحة العمل',
  'guide.description': 'تصفّح ملفات مساحة عمل هذه الجلسة',
  loading: 'جارٍ القراءة…',
  empty: 'مجلد فارغ',
  truncated: 'عدد العناصر كبير، يتم عرض جزء منها فقط.',
  noWorkspace: 'لا توجد مساحة عمل لهذه الجلسة.',
  reload: 'إعادة القراءة',
  'entry.other': 'هذا ليس ملفًا أو مجلدًا، ولا يمكن فتحه.',
  'error.notFound': 'لم يعد هذا المجلد موجودًا. ربما تم نقله أو حذفه.',
  'error.outsideWorkspace': 'هذا المجلد خارج مساحة العمل، لذا لن يقرأه الشريط الجانبي.',
  'error.notDirectory': 'هذا ليس مجلدًا.',
  'error.unavailable': 'فشل القراءة: {message}',
} as const
