/** Arabic dictionary for sidebarTerminal (zh/en). Generated by translate2.py. */
export const ar = {
  recoveryFailed: 'فشل استعادة الطرفية: {message}', retryRecovery: 'إعادة محاولة استعادة الطرفية',
  shell: 'اختيار Shell', shellLoading: 'جارٍ قراءة Shell…', shellEmpty: 'لا توجد Shell متاحة', description: 'تشغيل الأوامر في مساحة عمل الجلسة',
  title: 'الطرفية', new: 'طرفية جديدة', loading: 'جارٍ قراءة بيئة الطرفية…', creating: 'جارٍ التشغيل…',
  connecting: 'جارٍ الاتصال…', disconnected: 'تم قطع الاتصال.', reconnect: 'إعادة الاتصال',
  readonly: 'هذا العرض للقراءة فقط حاليًا.', control: 'السيطرة على الإدخال',
  closed: 'تم إغلاق الطرفية.', exited: 'انتهت العملية ({code})', failed: 'خطأ في الطرفية: {message}',
  rename: 'اسم الطرفية', unavailable: 'غير متوفر', retry: 'إعادة المحاولة',
  cleanupFailed: 'تعذّر إنهاء الطرفية «{title}»: {message}',
  missingTerminal: 'لم تعد هذه الطرفية موجودة، أنشئ طرفية جديدة.',
  inputFull: 'مخزن الإدخال ممتلئ، أعد الاتصال ثم حاول مرة أخرى.',
  attachmentEnded: 'انتهى اتصال الطرفية، أعد الاتصال للمتابعة.',
  invalidOutput: 'حدث خطأ في نقل شاشة الطرفية، أعد الاتصال.',
  terminalLimit: 'تم بلوغ الحد الأقصى لعدد الطرفيات، أغلق الطرفيات غير المستخدمة ثم حاول مرة أخرى. تُحتسب الطرفيات المنتهية ضمن العدد.',
} as const
