/** Arabic dictionary for skill (zh/en). Generated by translate2.py. */
export const ar = {
  'row.title': 'مهارة',
  'row.running': 'جارٍ تحميل المهارة',
  'row.failed': 'فشل تحميل المهارة',
  'row.stopped': 'تم إيقاف تحميل المهارة',
  'row.instructions': 'التعليمات',
  'row.inspect': 'فحص',
  'menu.userOnly': 'للمستخدم فقط',
} as const
