/** Arabic dictionary for slash.menu (zh/en). Generated by translate2.py. */
export const ar = {
  'command': 'الأوامر',
  'skill': 'المهارات',
  'subagent': 'الوكلاء الفرعيون',
  'loading': 'جارٍ التحميل…',
  'drill.aria': 'تصفح المجلد',
  'drill.hint': 'تصفح المجلد',
  'drill.key': 'Tab',
  'crumbs.aria': 'التنقل بين المجلدات',
  'suggestions.aria': 'عرض الاقتراحات',
} as const
